"""Hyperion-managed schedules: systemd service/timer pairs.

Definitions are validated fully before any write, installed through the
privileged ops helper into a dedicated allowlisted unit-file namespace,
reloaded and enabled through the same boundary, and reverted to the previous
valid pair if any step fails. A revision enables optimistic concurrency.
"""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Protocol

from ..models import ManagedScheduleDefinition, ManagedScheduleView
from .activity import ActivityStore

logger = logging.getLogger("hyperion.schedules.managed")

_MANAGED_PREFIX = "hyperion-"
_SAFE_NAME = re.compile(r"^[a-z][a-z0-9-]*$")

_SERVICE_TEMPLATE = """\
# Generated by Hyperion — do not edit directly.
[Unit]
Description={description}
{after}

[Service]
Type=oneshot
User={user}
{working_directory}ExecStart={executable}{arguments}
TimeoutStartSec={timeout}
"""

_TIMER_TEMPLATE = """\
# Generated by Hyperion — do not edit directly.
[Unit]
Description={description}

[Timer]
OnCalendar={on_calendar}
{missed}Persistent=false
Unit={service_unit}

[Install]
WantedBy=timers.target
"""


@dataclass
class ManagedScheduleState:
    definitions: dict[str, ManagedScheduleView] = field(default_factory=dict)


class ManagedScheduleError(ValueError):
    """Raised when a definition or privileged operation fails validation."""


class OpsHelper(Protocol):
    """The privileged boundary the manager talks to for every systemd action."""

    async def request(
        self, unit: str, operation: str, content: str | None = None
    ) -> dict[str, object]: ...


class ManagedScheduleManager:
    """Owns managed schedule definitions, privileged writes, and revisions."""

    def __init__(
        self,
        state_dir: Path,
        activity: ActivityStore,
        *,
        helper: OpsHelper,
        managed_unit_dir: Path,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        self._state_path = state_dir / "managed-schedules.json"
        self._activity = activity
        self._helper = helper
        self._managed_unit_dir = Path(managed_unit_dir)
        self._clock = clock or (lambda: datetime.now(UTC))
        self._state = self._load()

    def _load(self) -> ManagedScheduleState:
        try:
            raw = json.loads(self._state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return ManagedScheduleState()
        definitions: dict[str, ManagedScheduleView] = {}
        for name, value in raw.items():
            try:
                definitions[name] = ManagedScheduleView.model_validate(value)
            except Exception:
                logger.warning("discarding invalid managed schedule %s", name)
        return ManagedScheduleState(definitions=definitions)

    def _save(self) -> None:
        self._state_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            name: view.model_dump(mode="json", by_alias=True)
            for name, view in sorted(self._state.definitions.items())
        }
        tmp = self._state_path.with_suffix(".tmp")
        tmp.write_text(
            json.dumps(payload, sort_keys=True, indent=2), encoding="utf-8"
        )
        tmp.replace(self._state_path)

    def list(self) -> list[ManagedScheduleView]:
        return sorted(
            self._state.definitions.values(),
            key=lambda view: view.definition.name,
        )

    def get(self, name: str) -> ManagedScheduleView | None:
        return self._state.definitions.get(name)

    def unit_names(self, name: str) -> tuple[str, str]:
        return f"{_MANAGED_PREFIX}{name}.service", f"{_MANAGED_PREFIX}{name}.timer"

    async def create(
        self, definition: ManagedScheduleDefinition, identity: str
    ) -> ManagedScheduleView:
        return await self._write(definition, revision=0, identity=identity, installing=True)

    async def update(
        self,
        name: str,
        definition: ManagedScheduleDefinition,
        expected_revision: int,
        identity: str,
    ) -> ManagedScheduleView:
        existing = self._state.definitions.get(name)
        if existing is None:
            raise ManagedScheduleError(f"managed schedule {name!r} does not exist")
        if expected_revision != existing.revision:
            raise ManagedScheduleError(
                f"stale revision: expected {existing.revision}, got {expected_revision}"
            )
        return await self._write(
            definition, revision=existing.revision + 1, identity=identity, installing=False
        )

    async def delete(self, name: str, expected_revision: int, identity: str) -> None:
        existing = self._state.definitions.get(name)
        if existing is None:
            raise ManagedScheduleError(f"managed schedule {name!r} does not exist")
        if expected_revision != existing.revision:
            raise ManagedScheduleError(
                f"stale revision: expected {existing.revision}, got {expected_revision}"
            )
        service_unit, timer_unit = self.unit_names(name)
        previous = self._snapshot(name)
        try:
            await self._remove_files(service_unit, timer_unit)
            await self._daemon_reload()
        except Exception as exc:
            await self._restore_snapshot(name, previous)
            raise ManagedScheduleError(f"delete failed and was rolled back: {exc}") from exc
        del self._state.definitions[name]
        self._save()
        self._activity.record(
            "schedule_change",
            name,
            f"Managed schedule {name} deleted.",
            result="info",
            identity=identity,
            target_type="schedule",
            evidence={"revision": str(existing.revision)},
        )

    async def _write(
        self,
        definition: ManagedScheduleDefinition,
        revision: int,
        identity: str,
        installing: bool,
    ) -> ManagedScheduleView:
        self._validate(definition)
        service_unit, timer_unit = self.unit_names(definition.name)
        view = ManagedScheduleView(
            definition=definition,
            revision=revision,
            enabled=True,
            service_unit=service_unit,
            timer_unit=timer_unit,
            installed=False,
            last_result="unknown",
            last_run=None,
        )
        previous = self._snapshot(definition.name)
        try:
            await self._write_units(view)
            await self._daemon_reload()
            await self._enable_timer(definition.name)
        except Exception as exc:
            await self._restore_snapshot(definition.name, previous)
            raise ManagedScheduleError(f"schedule write failed and was rolled back: {exc}") from exc
        view.installed = True
        self._state.definitions[definition.name] = view
        self._save()
        action = "created" if installing else "updated"
        self._activity.record(
            "schedule_change",
            definition.name,
            f"Managed schedule {definition.name} {action}.",
            result="info",
            identity=identity,
            target_type="schedule",
            evidence={"revision": str(revision)},
        )
        return view

    def _validate(self, definition: ManagedScheduleDefinition) -> None:
        if not _SAFE_NAME.fullmatch(definition.name):
            raise ManagedScheduleError("name must match ^[a-z][a-z0-9-]*$")
        if not definition.on_calendar.strip():
            raise ManagedScheduleError("on_calendar is required")
        # Validate the calendar expression before writing anything.
        self._validate_calendar(definition.on_calendar)
        executable = definition.executable
        if not executable.startswith("/") or " " in executable:
            raise ManagedScheduleError("executable must be an absolute path without spaces")
        for argument in definition.arguments:
            if "\n" in argument or "\r" in argument:
                raise ManagedScheduleError("arguments must not contain newlines")
            if re.search(r"[;&|`$<>]", argument):
                raise ManagedScheduleError(
                    "arguments must not contain shell metacharacters"
                )

    def _validate_calendar(self, expression: str) -> None:
        """Accept a bounded set of systemd calendar forms.

        Full `systemd-analyze calendar` support is desirable but must not be a
        shell gateway; the parser here admits the common forms and rejects
        anything that looks like a path, command, or shell fragment.
        """
        stripped = expression.strip()
        if not re.fullmatch(r"[A-Za-z0-9*,\-/:. ]+", stripped):
            raise ManagedScheduleError("unsupported calendar expression")
        if stripped.startswith(("..", "./", "/", "-")):
            raise ManagedScheduleError("calendar expression must not be a path")
        # Reject shell metacharacters and newline injection; spaces are legal
        # in systemd calendar expressions like "*-*-* 02:00:00".
        if re.search(r"[;&|`$<>\n\r]", stripped):
            raise ManagedScheduleError("calendar expression must not contain shell syntax")

    async def _write_units(self, view: ManagedScheduleView) -> None:
        definition = view.definition
        service_text = _SERVICE_TEMPLATE.format(
            description=_escape(definition.description),
            after="",
            user=definition.user,
            working_directory=(
                f"WorkingDirectory={definition.working_directory}\n"
                if definition.working_directory
                else ""
            ),
            executable=definition.executable,
            arguments=(
                " " + " ".join(_quote(arg) for arg in definition.arguments)
                if definition.arguments
                else ""
            ),
            timeout=definition.timeout_seconds,
        )
        timer_text = _TIMER_TEMPLATE.format(
            description=_escape(definition.description),
            on_calendar=definition.on_calendar,
            missed=(
                "RemainAfterElapse=yes\n" if definition.missed_run_behavior == "catch_up" else ""
            ),
            service_unit=view.service_unit,
        )
        await self._helper_request(view.service_unit, "write-unit", content=service_text)
        await self._helper_request(view.timer_unit, "write-unit", content=timer_text)

    async def _helper_request(
        self, unit: str, operation: str, content: str | None = None
    ) -> None:
        try:
            result = await self._helper.request(unit, operation, content=content)
        except (OSError, ConnectionError, TimeoutError) as exc:
            raise ManagedScheduleError(f"privileged helper unavailable: {exc}") from exc
        if not result.get("ok", False):
            error = str(result.get("error", "unknown error"))
            raise ManagedScheduleError(f"privileged operation {operation} failed: {error}")

    async def _daemon_reload(self) -> None:
        await self._helper_request("", "daemon-reload")

    async def _enable_timer(self, name: str) -> None:
        _, timer_unit = self.unit_names(name)
        await self._helper_request(timer_unit, "enable-now")

    async def _remove_files(self, service_unit: str, timer_unit: str) -> None:
        await self._helper_request(service_unit, "remove-unit")
        await self._helper_request(timer_unit, "remove-unit")

    def _snapshot(self, name: str) -> dict[str, tuple[Path, str]]:
        service_unit, timer_unit = self.unit_names(name)
        directory = self._unit_dir()
        result: dict[str, tuple[Path, str]] = {}
        for unit in (service_unit, timer_unit):
            path = directory / unit
            if path.exists():
                try:
                    result[unit] = (path, path.read_text(encoding="utf-8"))
                except OSError:
                    pass
        return result

    async def _restore_snapshot(
        self, name: str, snapshot: dict[str, tuple[Path, str]]
    ) -> None:
        service_unit, timer_unit = self.unit_names(name)
        for unit in (service_unit, timer_unit):
            try:
                if unit in snapshot:
                    await self._helper_request(unit, "write-unit", content=snapshot[unit][1])
                else:
                    await self._helper_request(unit, "remove-unit")
            except Exception as exc:
                logger.error("could not restore %s: %s", unit, exc)
        try:
            await self._daemon_reload()
        except Exception as exc:
            logger.error("daemon-reload after restore failed: %s", exc)

    def _unit_dir(self) -> Path:
        return self._managed_unit_dir


def _escape(value: str) -> str:
    return value.replace("\n", " ").replace("\r", " ").strip()


def _quote(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_./@:+,\-=]+", value):
        return value
    return '"' + value.replace('"', '\\"') + '"'
